version: '3.8'
services:
  app:
    build: .
    volumes:
      - detections_volume:/app/logs
    environment:
      - RTSP_STREAM=${RTSP_STREAM}
      - DETECTION_TYPE=${DETECTION_TYPE}
volumes:
  detections_volume:

